name: Codeception Tests

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        php: [ 8.2, 8.3, 8.4 ]
        WP_VERSION: [ latest, nightly ]
        include:
          - php: 8.4
            WP_VERSION: 6.6
          - php: 8.3
            WP_VERSION: 6.7
          - php: 8.3
            WP_VERSION: 6.6
          - php: 8.4
            WP_VERSION: 6.7



    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Start wp-env
        uses: godaddy-wordpress/setup-wp-env@v1
        with:
          core: 'WordPress/WordPress#${{ matrix.WP_VERSION }}'
          phpVersion: ${{ matrix.php }}
          plugins: [ './tests/dws-framework-bootstrapper-test-plugin' ]
