name: Codeception Tests

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  test:
    env:
      # Must match the environment variables in the .dist.env file
      WORDPRESS_ROOT_DIR: /tmp/wordpress
      WORDPRESS_DB_URL: mysql://root:password@localhost:3306/wordpress_test
      TEST_TABLE_PREFIX: test_
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_URL: http://localhost:8888
      WORDPRESS_DOMAIN: localhost:8888
      WORDPRESS_ADMIN_PATH: /wp-admin
      WORDPRESS_ADMIN_USERNAME: admin
      WORDPRESS_ADMIN_PASSWORD: password
      CHROMEDRIVER_HOST: localhost
      CHROMEDRIVER_PORT: 4444

    strategy:
      fail-fast: false
      matrix:
        php: [ 7.2, 7.3, 7.4, 8.0, 8.1, 8.2, 8.3, 8.4 ]
        WP_VERSION: [ latest, nightly ]
        include:
          - php: 8.4
            WP_VERSION: 6.6
          - php: 8.3
            WP_VERSION: 6.7
          - php: 8.3
            WP_VERSION: 6.6
          - php: 8.4
            WP_VERSION: 6.7

    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306
        env:
          MYSQL_DATABASE: wordpress_test
          MYSQL_ROOT_PASSWORD: password
          options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Setup proper PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer

      - name: Setup WP CLI tools
        run: |
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          chmod +x wp-cli.phar
          mv wp-cli.phar /usr/local/bin/wp

      - name: Install WordPress
        run: |
          cd $WORDPRESS_ROOT_DIR
          wp core download --version=${{ matrix.WP_VERSION }}
          wp config create --dbname="wordpress_test" --dbuser="root" --dbpass="password" --dbhost="localhost" --dbprefix="$WORDPRESS_TABLE_PREFIX"
          wp core install --url="$WORDPRESS_URL" --title="Test" --admin_user="$WORDPRESS_ADMIN_USERNAME" --admin_password="$WORDPRESS_ADMIN_PASSWORD" --admin_email="admin@test.com" --skip-email
          wp rewrite structure '/%postname%/' --hard
          wp core update-db

      - name: Copy the plugin to the plugins directory
        run: |
          cp -r $GITHUB_WORKSPACE/tests/Support/dws-framework-bootstrapper-test-plugin $WORDPRESS_ROOT_DIR/wp-content/plugins/dws-framework-bootstrapper-test-plugin/
          composer update --no-dev --no-interaction --ignore-platform-reqs --working-dir=$WORDPRESS_ROOT_DIR/wp-content/plugins/dws-framework-bootstrapper-test-plugin/
          chmod -R 777 $WP_ROOT_FOLDER

      - name: Activate the test plugin
        run: |
          cd $WORDPRESS_ROOT_DIR
          wp plugin activate dws-framework-bootstrapper-test-plugin
          wp plugin list --status=active

      - name: Generate DB export
        run: wp db export $GITHUB_WORKSPACE/tests/Support/Data/dump.sql --path=$WORDPRESS_ROOT_DIR

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer run-script packages-install

      - name: Start a web server
        run: |
          php -S "$WORDPRESS_DOMAIN" -t "$WORDPRESS_ROOT_DIR" >/dev/null 2>&1 &
          phantomjs --webdriver=$CHROMEDRIVER_PORT >/dev/null 2>&1 &

      - name: Run Codeception tests
        run: composer run-script test
