name: Codeception Tests

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        php: [ 7.2, 7.3, 7.4, 8.0, 8.1, 8.2, 8.3, 8.4 ]
        WP_VERSION: [ latest, nightly ]
        include:
          - php: 8.4
            WP_VERSION: 6.6
          - php: 8.3
            WP_VERSION: 6.7
          - php: 8.3
            WP_VERSION: 6.6
          - php: 8.4
            WP_VERSION: 6.7

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: "5.7"

      - name: Install WordPress
        id: install-wordpress
        uses: holyhope/install-wordpress-github-action@main
        with:
          wordpress_version: ${{ matrix.WP_VERSION }}
          php_version: ${{ matrix.php }}

      - name: Setup Codeception environment
        run: |
          echo "WORDPRESS_ROOT_DIR=${{ steps.install-wordpress.outputs.path }}" >> $GITHUB_ENV
          echo "WORDPRESS_DB_URL=mysql://${{ steps.install-wordpress.outputs.db_user }}:${{ steps.install-wordpress.outputs.db_pass }}@${{ steps.install-wordpress.outputs.db_host }}:${{ steps.install-wordpress.outputs.db_port }}/${{ steps.install-wordpress.outputs.db_name }}" >> $GITHUB_ENV
          echo "TEST_TABLE_PREFIX=test_" >> $GITHUB_ENV
          echo "WORDPRESS_TABLE_PREFIX=wp_" >> $GITHUB_ENV
          echo "WORDPRESS_URL=http://localhost" >> $GITHUB_ENV
          echo "WORDPRESS_DOMAIN=localhost" >> $GITHUB_ENV
          echo "WORDPRESS_ADMIN_PATH=/wp-admin" >> $GITHUB_ENV
          echo "WORDPRESS_ADMIN_USERNAME=${{ steps.install-wordpress.outputs.admin_username }}" >> $GITHUB_ENV
          echo "WORDPRESS_ADMIN_PASSWORD=${{ steps.install-wordpress.outputs.admin_password }}" >> $GITHUB_ENV
          echo "CHROMEDRIVER_HOST=localhost" >> $GITHUB_ENV
          echo "CHROMEDRIVER_PORT=4444" >> $GITHUB_ENV

      - name: Copy the plugin to the plugins directory
        run: |
          cp -r $GITHUB_WORKSPACE/tests/Support/dws-framework-bootstrapper-test-plugin $WORDPRESS_ROOT_DIR/wp-content/plugins/dws-framework-bootstrapper-test-plugin/
          composer update --no-dev --no-interaction --ignore-platform-reqs --working-dir=$WORDPRESS_ROOT_DIR/wp-content/plugins/dws-framework-bootstrapper-test-plugin/
          chmod -R 777 $WORDPRESS_ROOT_DIR

      - name: Activate the test plugin
        run: |
          cd $WORDPRESS_ROOT_DIR
          wp plugin activate dws-framework-bootstrapper-test-plugin
          wp plugin list --status=active

      - name: Generate DB export
        run: ${{ steps.install-wordpress.outputs.wp_cli }} db export $GITHUB_WORKSPACE/tests/Supports/Data/dump.sql --path=$WORDPRESS_ROOT_DIR

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer run-script packages-install

      - name: Start a web server
        run: |
          php -S "localhost" -t "$WORDPRESS_ROOT_DIR" >/dev/null 2>&1 &
          phantomjs --webdriver=4444 >/dev/null 2>&1 &

      - name: Run Codeception tests
        run: composer run-script test
